---
# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.0
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: roxygenize
        additional_dependencies:
          - checkmate
          - knitr
          - testthat
          - Rdpack
          - etm
          - openpharma/roxytypes
          - openpharma/roxylint
      - id: use-tidy-description
      - id: spell-check
        exclude: >
          (?x)^(
          data/.*|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)DESCRIPTION|
          (.*/|)WORDLIST|
          (.*/|)LICENSE|
          (.*/|)\.Rbuildignore|
          (.*/|)\.lintr|
          (.*/|)_pkgdown.yaml|
          (.*/|)staged_dependencies.yaml|
          (.*/|)\.pre-commit-.*|
          \.github/.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.png|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData
          )$
      - id: lintr
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: deps-in-desc
        exclude: >
          (?x)^(
          data-raw/.*
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: >
          (?x)^(
          README.md
          )$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: end-of-file-fixer
        exclude: '\.Rd'
      - id: trailing-whitespace
        exclude: >
          (?x)^(
          .*\.Rd|
          README.md
          )$
      - id: check-yaml
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: check-symlinks
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        exclude: >
          (?x)^(
          README.md|
          NEWS.md
          )$
